### ISSUE TITLE
Avance del proyecto

### ISSUE THREAD

**Issue by bosqueinvierno** [natichan/scl-2018-05-bc-core-pm-datadashboard#3]
Holi! Vengo a dejar comentarios sobre el avance del proyecto 💃 

-  Ponganle weno! No hay una estructura base que soporte a los datos que deben traer a la pantalla. 
-  Con respecto a tu consulta de cómo pintar la información, quizás este link te pueda dar una idea de como comenzar a hacerlo https://es.stackoverflow.com/questions/47485/como-usar-un-api-con-javascript-y-la-funci%C3%B3n-fetch

**Comment by natichan** [comment]
Muchas gracias Alli, ya vamos a empezar con la estructura ahora que tenemos más claro como acceder a los datos. La página esta genial, la miraré más en profundo para trabajar en pintar la información. :smile:

**Comment by natichan** [comment]
Lista estructura base, por ahora, siempre puede mejorar. :dancer:
